language: ruby

rvm:
  - 2.0
  - 2.2.3
  - ruby-head
  - jruby-9.0.4.0

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_3.1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
