language: ruby

rvm:
  - 2.0
  - 2.2.3
  - ruby-head

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_3.1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
